# Generated by Django 5.1.2 on 2024-12-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age_range', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='SportDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('vat_number', models.CharField(max_length=11, unique=True, verbose_name='Partita IVA')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medici',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
            ],
            options={
                'verbose_name': 'Allenatore',
                'verbose_name_plural': 'Allenatori',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('date_of_birth', models.DateField(verbose_name='Data di Nascita')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='profiles.category', verbose_name='Categoria')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='profiles.trainer', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
            },
        ),
    ]
