# Generated by Django 5.1.2 on 2025-01-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_name_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='profiles.category', verbose_name='Categoria'),
        ),
    ]
