# Generated by Django 5.1.2 on 2024-12-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=50, verbose_name='Identificativo Struttura Erogatrice')),
                ('issued_date', models.DateField(verbose_name='Data di Emissione')),
                ('expiration_date', models.DateField(verbose_name='Data di Scadenza')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.sportdoctor', verbose_name='Medico')),
            ],
            options={
                'verbose_name': 'Certificato Medico Sportivo',
                'verbose_name_plural': 'Certificati Medico Sportivi',
                'ordering': ['-issued_date'],
            },
        ),
    ]
