# Generated by Django 4.2.4 on 2023-08-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
