# Generated by Django 5.1.2 on 2024-11-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_active_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
    ]
